# Generated by Django 5.2 on 2025-05-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("uploaded_file", models.FileField(upload_to="articles/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("txt", "TXT")], max_length=30
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArticleAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("objectives", models.TextField(blank=True, null=True)),
                ("methodology", models.TextField(blank=True, null=True)),
                ("conclusions", models.TextField(blank=True, null=True)),
                ("suggested_field", models.CharField(blank=True, null=True)),
                ("analysis_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="analyzer.article",
                    ),
                ),
            ],
        ),
    ]
